version: '3.7'

services:

  grpcserver:
    image: ${GRPC_SERVER_IMAGE}
    container_name: grpc_server
    command: /usr/local/bin/server
    ports:
      - 9000:9000
    volumes:
      - $PWD/testdata:/var/blocks
    networks:
      - local

  defaultserver:
    image: postgres:15.1
    container_name: defaultserver
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - $PWD/tmp/pgdata:/var/lib/postgresql/data
    networks:
      - local

  devops:
    image: dpage/pgadmin4:7.8
    container_name: devops
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@psql.email
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      defaultserver:
        condition: service_started
    networks:
      - local
      
networks:
  local:
    name: $NETWORK